package com.wordmemo.app.ui.screen.wordgraph

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.wordmemo.app.data.local.WordMemoDatabase
import com.wordmemo.app.domain.model.Word
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.math.*

data class GraphNode(
    val id: String,
    val label: String,
    val chinese: String = "",
    val level: Int = 0,       // 0=center, 1=L1, 2=L2
    val type: String = "",    // synonym, antonym, collocation, similar, concept
    val parentId: String? = null,
    val branchIndex: Int = 0
)

data class GraphEdge(
    val from: String,
    val to: String,
    val label: String = ""
)

data class MultiLevelGraph(
    val centerWord: String = "",
    val nodes: List<GraphNode> = emptyList(),
    val edges: List<GraphEdge> = emptyList()
)

data class WordGraphUiState(
    val centerWord: Word? = null,
    val graph: MultiLevelGraph = MultiLevelGraph(),
    val isLoading: Boolean = true,
    val error: String? = null,
    val bookmarkedLabels: Set<String> = emptySet(),
    val lastBookmarked: String? = null
)

class WordGraphViewModel(application: Application) : AndroidViewModel(application) {

    private val _uiState = MutableStateFlow(WordGraphUiState())
    val uiState: StateFlow<WordGraphUiState> = _uiState.asStateFlow()

    fun loadWord(wordId: Long) {
        viewModelScope.launch {
            _uiState.value = WordGraphUiState(isLoading = true)

            try {
                val db = WordMemoDatabase.getInstance(getApplication())
                val entity = withContext(Dispatchers.IO) { db.wordDao().getById(wordId) }

                if (entity == null) {
                    _uiState.value = WordGraphUiState(isLoading = false, error = "单词未找到")
                    return@launch
                }

                val word = Word(
                    id = entity.id, english = entity.english,
                    chinese = entity.chinese.ifBlank { "待补充" },
                    phonetic = entity.phonetic,
                    note = entity.note, createdAt = entity.createdAt,
                    updatedAt = entity.updatedAt
                )

                // 以数据库中真实单词为中心，动态生成关系图谱
                val graph = withContext(Dispatchers.Default) {
                    buildGraph(word.english, word.chinese)
                }

                _uiState.value = WordGraphUiState(
                    centerWord = word,
                    graph = graph,
                    isLoading = false
                )

            } catch (e: Exception) {
                _uiState.value = WordGraphUiState(
                    isLoading = false,
                    error = "加载失败: ${e.message}"
                )
            }
        }
    }

    // ─── 动态图谱生成：以任意中心词生成1+7+14径向树 ───

    private fun buildGraph(center: String, chinese: String): MultiLevelGraph {
        val seed = center.lowercase().hashCode().toLong()
        val rng = java.util.Random(seed)

        val allNodes = mutableListOf<GraphNode>()
        val allEdges = mutableListOf<GraphEdge>()

        // 中心节点
        allNodes.add(GraphNode(
            id = "center", label = center, chinese = chinese,
            level = 0, type = "center"
        ))

        // 可用词汇池：来自chineseMap（保证都有中文释义）
        val available = chineseMap.keys
            .filter { it != center.lowercase() }
            .toMutableList()

        // 从chineseMap中选7个L1词
        val typeCycle = listOf("synonym", "antonym", "collocation", "similar", "concept", "synonym", "antonym")
        val l1Picked = mutableListOf<String>()

        for (branch in 0 until 7) {
            if (available.isEmpty()) break
            val idx = (rng.nextInt() and Int.MAX_VALUE) % available.size
            val word = available.removeAt(idx)
            l1Picked.add(word)

            val l1Id = "l1_$branch"
            val l1Chinese = chineseMap[word] ?: word.replaceFirstChar { it.uppercase() }
            allNodes.add(GraphNode(
                id = l1Id, label = word, chinese = l1Chinese,
                level = 1, type = typeCycle[branch % typeCycle.size],
                branchIndex = branch
            ))
            allEdges.add(GraphEdge(from = "center", to = l1Id, label = typeCycle[branch % typeCycle.size]))

            // 为每个L1选2个L2子节点
            for (childIdx in 0 until 2) {
                if (available.isEmpty()) break
                val cIdx = (rng.nextInt() and Int.MAX_VALUE) % available.size
                val childWord = available.removeAt(cIdx)
                val childChinese = chineseMap[childWord] ?: childWord.replaceFirstChar { it.uppercase() }

                val l2Id = "l2_${branch}_$childIdx"
                val childType = typeCycle[(branch + childIdx + 1) % typeCycle.size]
                allNodes.add(GraphNode(
                    id = l2Id, label = childWord, chinese = childChinese,
                    level = 2, type = childType, parentId = l1Id,
                    branchIndex = branch
                ))
                allEdges.add(GraphEdge(from = l1Id, to = l2Id, label = childType))
            }
        }

        return MultiLevelGraph(centerWord = center, nodes = allNodes, edges = allEdges)
    }

    /** 简易中文释义查找（演示用） */
    private fun lookupChinese(word: String): String {
        val lower = word.lowercase()
        chineseMap[lower]?.let { return it }
        return word.replaceFirstChar { it.uppercase() }
    }

    fun addWordToBook(label: String, chinese: String = "") {
        viewModelScope.launch {
            if (label in _uiState.value.bookmarkedLabels) return@launch
            try {
                val phonetic = lookupPhonetic(label)
                val db = WordMemoDatabase.getInstance(getApplication())
                val existing = withContext(Dispatchers.IO) {
                    db.wordDao().search("%$label%").firstOrNull()
                }
                if (existing != null) {
                    _uiState.value = _uiState.value.copy(
                        bookmarkedLabels = _uiState.value.bookmarkedLabels + label,
                        lastBookmarked = label
                    )
                    return@launch
                }
                val now = System.currentTimeMillis()
                val wid = withContext(Dispatchers.IO) {
                    db.wordDao().insert(com.wordmemo.app.data.local.entity.WordEntity(
                        english = label, chinese = chinese, phonetic = phonetic,
                        note = "来自关系图谱",
                        createdAt = now, updatedAt = now
                    ))
                }
                withContext(Dispatchers.IO) {
                    com.wordmemo.app.data.local.entity.FlashcardEntity(
                        wordId = wid, state = "NEW", due = now
                    ).let { db.flashcardDao().insert(it) }
                }
                _uiState.value = _uiState.value.copy(
                    bookmarkedLabels = _uiState.value.bookmarkedLabels + label,
                    lastBookmarked = label
                )
            } catch (_: Exception) { }
        }
    }

    private fun lookupPhonetic(word: String): String {
        val lower = word.lowercase()
        phoneticMap[lower]?.let { return it }
        // 未收录则尝试映射
        return ""
    }

    fun navigateToWord(label: String) {
        viewModelScope.launch {
            try {
                val db = WordMemoDatabase.getInstance(getApplication())
                val entity = withContext(Dispatchers.IO) {
                    db.wordDao().search("%$label%").firstOrNull()
                }
                if (entity != null) loadWord(entity.id)
            } catch (_: Exception) { }
        }
    }

    // ═══════════════════════════════════════════
    //  词汇池
    // ═══════════════════════════════════════════

    private val synonymPool = listOf(
        "abundant", "accurate", "brave", "brief", "bright", "calm", "careful",
        "certain", "clear", "clever", "common", "complex", "constant", "cool",
        "creative", "crucial", "curious", "deep", "dense", "diverse",
        "eager", "efficient", "elastic", "elegant", "endless", "energetic",
        "enormous", "essential", "exact", "fancy", "fast", "fierce", "firm",
        "flexible", "fluent", "formal", "frank", "frequent", "fresh", "full",
        "generous", "gentle", "genuine", "glad", "graceful", "grand", "grateful",
        "great", "happy", "harsh", "healthy", "heavy", "helpful", "honest",
        "humble", "immense", "intense", "keen", "kind", "lively", "logical",
        "loose", "lovely", "loyal", "lucky", "massive", "mature", "mild",
        "minimal", "minor", "modest", "narrow", "neat", "noble", "normal",
        "novel", "obvious", "odd", "optimal", "ordinary", "original", "passive",
        "patient", "perfect", "polite", "popular", "precise", "pretty", "proud",
        "pure", "quick", "quiet", "rapid", "rare", "raw", "ready", "real",
        "rich", "rigid", "ripe", "robust", "rough", "routine", "sacred", "safe",
        "scarce", "secure", "severe", "shallow", "sharp", "sheer", "short",
        "shy", "silly", "simple", "sincere", "skilled", "slim", "smooth",
        "social", "soft", "solid", "spare", "stable", "steady", "steep",
        "stern", "stiff", "still", "straight", "strange", "strict", "sturdy",
        "subtle", "sudden", "sufficient", "suitable", "sunny", "super", "sure",
        "sweet", "swift", "tall", "tame", "tender", "thick", "thin", "thorough",
        "tight", "tiny", "tough", "true", "trusty", "unique", "universal",
        "urban", "useful", "vague", "valid", "vast", "vital", "vivid",
        "warm", "weak", "wealthy", "weary", "wide", "wild", "wise", "worthy"
    )

    private val antonymPool = listOf(
        "absent", "afraid", "artificial", "bitter", "blunt", "bold", "boring",
        "cheap", "clumsy", "coarse", "cold", "confused", "cruel", "crude",
        "dangerous", "dim", "dirty", "dishonest", "doubtful", "dull",
        "empty", "evil", "false", "feeble", "foolish", "foreign", "fragile",
        "funny", "generous", "gloomy", "greedy", "grim", "guilty", "harsh",
        "hateful", "humble", "ignorant", "immature", "impolite", "impure",
        "inferior", "innocent", "insane", "insecure", "jealous", "lazy",
        "loose", "lost", "loud", "low", "loyal", "mad", "mean", "messy",
        "miserable", "modest", "narrow", "naughty", "negative", "nervous",
        "noisy", "numb", "obscure", "old", "opposite", "ordinary", "outdoor",
        "painful", "passive", "petty", "plain", "poor", "proud", "pushy",
        "queer", "quick", "quiet", "raw", "reckless", "risky", "rough",
        "rude", "rusty", "sad", "scared", "secret", "selfish", "shallow",
        "shy", "sick", "silent", "silly", "simple", "sleepy", "slow",
        "small", "smooth", "soft", "solemn", "sore", "sour", "sparse",
        "stale", "stern", "stiff", "strange", "strict", "stubborn", "stupid",
        "sullen", "surly", "suspicious", "sweet", "swift", "tame", "tardy",
        "tense", "terrible", "thick", "thin", "tight", "timid", "tired",
        "tough", "tragic", "ugly", "unclear", "unequal", "unfair", "unfit",
        "unhappy", "unhealthy", "unknown", "unlikely", "unlucky", "unreal",
        "unruly", "unstable", "untrue", "unusual", "unwise", "unworthy",
        "upright", "useless", "vain", "vicious", "vulgar", "wasteful",
        "weak", "weary", "wicked", "wild", "willing", "windy", "witty",
        "worthy", "wrong", "young", "zero"
    )

    private val collocationPool = listOf(
        "absolute", "active", "actual", "annual", "apparent", "automatic", "available",
        "average", "aware", "basic", "beneficial", "binding", "blank", "blind",
        "broad", "busy", "capable", "central", "circular", "civil", "classic",
        "clinical", "closed", "collective", "commercial", "common", "complete",
        "comprehensive", "concrete", "confident", "conscious", "consistent",
        "continuous", "contractual", "convenient", "conventional", "correct",
        "critical", "cultural", "current", "daily", "deadly", "decent",
        "defensive", "definite", "delicate", "dependent", "detailed", "direct",
        "discrete", "distinct", "domestic", "dominant", "double", "dramatic",
        "dynamic", "eastern", "economic", "effective", "electric", "eligible",
        "emotional", "empirical", "empty", "endless", "entire", "environmental",
        "equal", "equivalent", "ethnic", "eventual", "evident", "exact",
        "excellent", "excess", "executive", "explicit", "extensive", "external",
        "extreme", "faint", "fair", "faithful", "familiar", "famous",
        "fatal", "favorable", "feasible", "federal", "female", "fertile",
        "final", "financial", "finite", "fiscal", "fixed", "flat", "fluid",
        "forced", "forecast", "foreign", "formal", "former", "foundational",
        "fragile", "free", "friendly", "front", "frozen", "full", "fundamental",
        "future", "general", "generic", "genetic", "global", "gradual",
        "gross", "growing", "guiding", "handy", "handsome", "hanging",
        "hard", "harmful", "harmless", "healthy", "heavy", "hidden",
        "hierarchical", "historic", "hollow", "home", "horizontal", "hostile",
        "hot", "huge", "human", "ideal", "identical", "illegal", "immediate",
        "immense", "immune", "implicit", "important", "impossible", "impressive",
        "independent", "indirect", "individual", "industrial", "inevitable",
        "infinite", "informal", "inherent", "initial", "inner", "innocent",
        "instant", "integral", "intellectual", "intense", "intensive",
        "interior", "intermediate", "internal", "international", "intimate",
        "invisible", "involved", "isolated", "joint", "junior", "just",
        "keen", "key", "known", "labor", "land", "large", "last", "late",
        "leading", "legal", "legitimate", "level", "liable", "liberal",
        "light", "likely", "limited", "linear", "linguistic", "liquid",
        "literal", "literary", "little", "live", "local", "logical",
        "long", "loose", "lost", "loud", "lovely", "low", "lower", "lucky",
        "mad", "magic", "main", "major", "male", "manageable", "manual",
        "marginal", "marine", "massive", "master", "material", "mature",
        "maximum", "measurable", "mechanical", "medical", "medieval",
        "medium", "mental", "mere", "mid", "middle", "mild", "military",
        "minimal", "minimum", "minor", "minute", "mixed", "mobile",
        "moderate", "modern", "modest", "molecular", "momentary", "monetary",
        "monthly", "moral", "mortal", "motional", "motor", "mounting",
        "multiple", "mutual", "mysterious", "naked", "narrow", "national",
        "native", "natural", "naval", "near", "nearby", "neat", "necessary",
        "negative", "neighboring", "neutral", "nice", "noble", "noisy",
        "nominal", "normal", "northern", "notable", "noted", "noticeable",
        "notorious", "novel", "nuclear", "numerous", "nutrient", "obedient",
        "objective", "obligatory", "obscure", "observant", "obsolete",
        "obvious", "occasional", "occupational", "odd", "offensive",
        "official", "open", "operational", "opposed", "opposite", "optical",
        "optional", "oral", "ordinary", "organic", "organizational",
        "original", "orthodox", "other", "outdoor", "outer", "outgoing",
        "outstanding", "overall", "overnight", "overseas", "overt",
        "overwhelming", "own", "pacific", "painful", "pale", "parallel",
        "partial", "particular", "partisan", "passionate", "passive",
        "past", "patient", "peaceful", "peculiar", "perceived", "perfect",
        "permanent", "permissible", "personal", "persuasive", "petty",
        "philosophical", "physical", "pink", "plain", "planned", "plausible",
        "pleasant", "pleased", "pleasing", "plentiful", "plural", "poetic",
        "pointed", "polite", "political", "poor", "popular", "portable",
        "positive", "possible", "potential", "powerful", "practical",
        "precious", "precise", "predictable", "preferred", "pregnant",
        "preliminary", "premier", "premium", "prepared", "present",
        "presidential", "pressing", "prestigious", "pretty", "prevailing"
    )

    private val similarPool = listOf(
        "abstract", "academic", "accurate", "active", "acute", "adept", "advanced",
        "adventurous", "affected", "affluent", "agile", "agreeable", "alert",
        "allied", "aloof", "amazing", "ambient", "ample", "amused", "ancient",
        "angelic", "angry", "animated", "annual", "anxious", "apparent", "appealing",
        "applicable", "appointed", "apt", "ardent", "arid", "aristocratic",
        "artistic", "ashamed", "assured", "astonishing", "athletic", "attached",
        "attentive", "attractive", "authentic", "authorized", "autonomous",
        "avid", "awesome", "awkward", "backward", "bankrupt", "barbaric",
        "bare", "barren", "basic", "beaming", "beautiful", "becoming",
        "befitting", "beginner", "behavioral", "belated", "beloved", "benevolent",
        "benign", "bespoke", "best", "better", "bewildered", "biased",
        "bigoted", "biting", "bitter", "bizarre", "black", "blameless",
        "blank", "blazing", "bleak", "blessed", "blind", "blissful",
        "blond", "bloody", "blooming", "blunt", "blushing", "boastful",
        "bold", "bony", "bored", "boring", "bossy", "both", "bouncy",
        "bound", "boundless", "brainy", "brash", "brave", "brawny",
        "breakable", "breathable", "breezy", "brief", "bright", "brilliant",
        "brisk", "brittle", "broad", "broken", "bronze", "brown", "bruised",
        "brutal", "bubbly", "bulky", "buoyant", "burdensome", "burly",
        "bustling", "busy", "buttery", "buzzing", "cagey", "calculating",
        "callous", "calm", "candid", "canine", "capable", "capital",
        "capricious", "captivating", "carefree", "careful", "careless",
        "caring", "cautious", "ceaseless", "celebrated", "certain",
        "changeable", "chanting", "characteristic", "charitable", "charming",
        "chaste", "chatty", "cheap", "cheerful", "cheesy", "chemical",
        "chief", "childish", "childlike", "chilly", "chipper",
        "chivalrous", "chubby", "chunky", "circular", "civic", "civil",
        "clandestine", "classic", "classy", "clean", "clear",
        "clever", "clinical", "closed", "cloudy", "clueless", "clumsy",
        "coarse", "cognitive", "coherent", "cold", "colorful", "colossal",
        "combined", "comic", "commanding", "commendable", "commercial",
        "common", "communal", "competent", "competitive", "complacent",
        "complete", "complex", "compliant", "composed", "comprehensive",
        "compulsory", "concealed", "concerned", "concise", "concurrent",
        "conditional", "confident", "confined", "confirmed", "confused",
        "congenial", "congested", "connected", "conscientious", "conscious",
        "consecutive", "conservative", "considerable", "consistent",
        "conspicuous", "constant", "constitutional", "constructive",
        "contagious", "contemporary", "content", "contentious", "contiguous",
        "continental", "continuous", "contracted", "contradictory",
        "contrary", "contrasting", "contributory", "controlled", "controversial",
        "convenient", "conventional", "conversant", "convinced", "convincing",
        "cooperative", "coordinated", "cordial", "corporate", "correct",
        "corresponding", "costly", "courageous", "courteous", "covert",
        "coveted", "cowardly", "cozy", "crafty", "cramped", "cranky",
        "crash", "crazy", "creamy", "creative", "credible", "creeping",
        "criminal", "crisp", "critical", "crooked", "crowded", "crucial",
        "crude", "cruel", "crushing", "cryptic", "crystalline", "cubic",
        "culinary", "cultivated", "cultural", "cumbersome", "curious",
        "curly", "current", "curt", "curved", "cushioned", "customary",
        "cutting", "cylindrical", "cynical", "dainty", "damaged",
        "damp", "dangerous", "dapper", "daring", "dark", "darling",
        "dazzling", "dead", "deadly", "deaf", "dear", "debatable",
        "decent", "decisive", "decorative", "deep", "defeated", "defective",
        "defensive", "defiant", "definite", "definitive", "degraded",
        "delayed", "delectable", "delicate", "delicious", "delighted",
        "delightful", "demanding", "democratic", "demonic", "dense",
        "dental", "dependent", "depressed", "deranged", "descriptive",
        "deserted", "deserved", "deserving", "designed", "desirable",
        "desolate", "desperate", "despised", "destined", "destructive",
        "detailed", "detached", "determined", "developing", "devoted",
        "devout", "dexterous", "diagonal", "different", "difficult",
        "diffuse", "digital", "dignified", "diligent", "dim", "diminutive",
        "diplomatic", "direct", "dirty", "disabled", "disastrous",
        "disciplined", "discontented", "discordant", "discovered",
        "discriminating", "discursive", "disdainful", "diseased",
        "disgraceful", "disgusted", "disheartened", "dishonest", "disloyal",
        "dismal", "dismissive", "disobedient", "disorderly", "disparate",
        "dispassionate", "dispensable", "displeased", "disposable",
        "disproportionate", "disputed", "disqualified", "disrespectful",
        "disruptive", "dissimilar", "distant", "distinct", "distinctive",
        "distinguished", "distorted", "distracted", "distressed",
        "distributive", "distrustful", "disturbed", "divergent", "diverse",
        "divine", "dizzy", "docile", "doctoral", "documented",
        "dogmatic", "domestic", "dominant", "domineering", "donated",
        "doomed", "dormant", "doubtful", "dowdy", "downcast", "downright",
        "downward", "dozen", "drab", "drafty", "dramatic", "drastic",
        "dreaded", "dreadful", "dreamy", "dreary", "drenched", "dressy",
        "drifting", "driven", "droll", "droopy", "drowsy", "drunk",
        "dry", "dual", "dubious", "duck", "due", "dull", "dumb",
        "durable", "dusky", "dusty", "dutiful", "dynamic", "dysfunctional",
        "eager", "early", "earnest", "earthly", "east", "eastern",
        "easy", "easygoing", "eatable", "eccentric", "echoing",
        "economic", "economical", "ecstatic", "edgy", "educated",
        "educational", "cerie", "effective", "efficient", "effortless",
        "egocentric", "eight", "eighth", "elaborate", "elastic", "elated",
        "elderly", "electric", "electrical", "electronic", "elegant",
        "elemental", "elementary", "elevated", "eleventh", "eligible",
        "elite", "eloquent", "elusive", "embarrassed", "embattled",
        "emotional", "emphatic", "empirical", "employable", "empty",
        "enabling", "enchanted", "enchanting", "encouraged", "encouraging",
        "endearing", "endless", "enduring", "energetic", "enforced",
        "engaged", "engaging", "engrossed", "enhanced", "enigmatic",
        "enjoyable", "enlightened", "enormous", "enough", "enraged",
        "ensuing", "entertained", "entertaining", "enthusiastic", "entire",
        "entitled", "entranced", "entrepreneurial", "enumerable",
        "envious", "environmental", "epic", "epidemic", "equal", "equitable",
        "equivalent", "erratic", "erroneous", "essential", "estimated",
        "eternal", "ethical", "ethnic", "evanescent", "even", "eventual",
        "everlasting", "everyday", "evident", "evil", "evocative",
        "exact", "exalted", "excellent", "exceptional", "excessive",
        "excited", "exciting", "exclusive", "exemplary", "exhausted",
        "exhaustive", "existent", "existing", "exotic", "expansive",
        "expected", "expedient", "expensive", "experienced", "expert",
        "expired", "explicit", "explosive", "exponential", "exposed",
        "expressive", "exquisite", "extended", "extensive", "external",
        "extinct", "extra", "extraordinary", "extravagant", "extreme",
        "exuberant", "fabulous", "facial", "facile", "factual", "faded",
        "faint", "fair", "faithful", "fake", "fallacious", "familiar",
        "famous", "fancy", "fantastic", "far", "fascinated", "fascinating",
        "fashionable", "fast", "fat", "fatal", "fateful", "fatherly",
        "fatigued", "faultless", "favorable", "favorite", "fearful",
        "fearless", "feasible", "feathered", "featured", "federal",
        "feeble", "female", "feminine", "ferocious", "fertile", "fervent",
        "festive", "feudal", "feverish", "few", "fictional", "fierce",
        "fiery", "fifth", "fifty", "fighting", "figured", "filthy",
        "final", "financial", "fine", "finished", "finite", "firm",
        "first", "fiscal", "fit", "fitting", "five", "fixed", "fizzy",
        "flabby", "flagrant", "flaky", "flamboyant", "flashy", "flat",
        "flattering", "flawed", "flawless", "fleet", "fleeting", "flexible",
        "flickering", "flimsy", "flippant", "floating", "flooded", "floral",
        "flourishing", "flowery", "flowing", "fluent", "fluffy", "fluid",
        "flushed", "flying", "foamy", "focal", "focused", "folk",
        "following", "fond", "foolish", "forbidding", "forced", "forceful",
        "foreign", "foremost", "forensic", "forgetful", "forgivable",
        "forgiving", "forgotten", "formal", "former", "formidable",
        "forthcoming", "fortified", "fortunate", "forty", "forward",
        "foul", "found", "four", "fourth", "fragile", "fragrant",
        "frail", "frank", "frantic", "fraudulent", "freak", "free",
        "frequent", "fresh", "fretful", "friendly", "frightened",
        "frightening", "frigid", "frivolous", "frizzy", "front", "frozen",
        "fruitful", "fruity", "frustrated", "fugitive", "fulfilled",
        "full", "fumbling", "functional", "fundamental", "funny",
        "furious", "furry", "further", "futile", "future", "fuzzy",
        "gabby", "gainful", "gala", "gallant", "galloping", "gaping",
        "garbled", "gardening", "gargantuan", "garish", "gaseous",
        "gastric", "gathered", "gaudy", "gaunt", "gauzy", "gawky",
        "general", "generous", "genetic", "genial", "gentle", "genuine",
        "geographic", "geological", "geometric", "germane", "giddy",
        "gifted", "gigantic", "giving", "glad", "glamorous", "glaring",
        "glass", "gleaming", "glib", "gliding", "glimmering", "glinting",
        "glistening", "glittering", "global", "gloomy", "glorious",
        "glossy", "glowing", "glum", "gluten", "gnarly", "gold",
        "golden", "good", "goodly", "gorgeous", "governing", "graceful",
        "gracious", "gradual", "grand", "grandiose", "graphic",
        "grateful", "gratified", "grating", "gratuitous", "grave",
        "gray", "greasy", "great", "greedy", "green", "gregarious",
        "grey", "grieving", "grim", "grimy", "gripping", "gritty",
        "grizzled", "groaning", "groggy", "groomed", "groovy", "gross",
        "grotesque", "grouchy", "grounded", "growing", "grown", "grueling",
        "gruesome", "gruff", "grumpy", "guarded", "guiltless", "guilty",
        "gullible", "gusty", "gutsy", "habitual", "hairless", "hairy",
        "half", "hallowed", "halting", "handy", "hanging", "hapless",
        "happy", "hard", "hardy", "harmful", "harmless", "harmonic",
        "harmonious", "harsh", "hasty", "hateful", "haunting", "hawkish",
        "hazardous", "hazy", "headed", "heady", "healing", "healthful",
        "healthy", "heartbreaking", "heartfelt", "hearty", "heated",
        "heathen", "heavenly", "heavy", "hectic", "hedonistic", "heightened",
        "heinous", "helpful", "helpless", "herbal", "hereditary",
        "heroic", "hesitant", "hidden", "hierarchical", "high", "highly",
        "hilarious", "hilly", "hip", "historical", "hollow", "holy",
        "home", "homeless", "homely", "homeopathic", "homesick", "honest",
        "honorable", "hopeful", "hopeless", "horizontal", "hormonal",
        "horned", "horrendous", "horrible", "horrific", "horrified",
        "hospitable", "hostile", "hot", "huge", "human", "humane",
        "humble", "humid", "humiliated", "humiliating", "humorous",
        "hundred", "hungry", "hunt", "hurried", "hurt", "hurtful",
        "husky", "hybrid", "hygienic", "hyper", "hypnotic", "hypocritical",
        "icy", "ideal", "idealistic", "identical", "identifiable",
        "ideological", "idiotic", "idle", "idolized", "ignorant",
        "ill", "illegal", "illiterate", "illustrious", "imaginary",
        "imaginative", "immediate", "immense", "immoral", "immune",
        "impartial", "impatient", "impeccable", "impenetrable", "imperative",
        "imperfect", "imperial", "impersonal", "impertinent", "impish",
        "implausible", "implicit", "implied", "impolite", "important",
        "imposing", "impossible", "impoverished", "impractical", "impressive",
        "improbable", "improper", "improved", "impulsive", "inactive",
        "inadequate", "inappropriate", "incapable", "incessant", "incipient",
        "incisive", "inclusive", "incoherent", "incoming", "incomplete",
        "inconclusive", "incongruous", "inconsequential", "inconsistent",
        "inconvenient", "incorrect", "increasing", "incredible",
        "incremental", "incurable", "indecisive", "indefinite", "independent",
        "indescribable", "indeterminate", "indicative", "indifferent",
        "indigenous", "indignant", "indirect", "indiscreet", "indiscriminate",
        "indispensable", "indistinct", "individual", "indoor", "inductive",
        "indulgent", "industrial", "industrious", "ineffective", "ineffectual",
        "inefficient", "inelegant", "ineligible", "inevitable", "inexcusable",
        "inexhaustible", "inexpensive", "inexperienced", "inexplicable",
        "inextricable", "infallible", "infamous", "infant", "infantile",
        "inferior", "infinite", "informal", "informed", "infrequent",
        "ingenious", "ingrained", "inherent", "initial", "injured",
        "injurious", "inland", "innate", "inner", "innocent", "innovative",
        "innumerable", "inorganic", "inpatient", "inquisitive", "insane",
        "insatiable", "insecure", "insensible", "insensitive", "insidious",
        "insignificant", "insistent", "insolvent", "insouciant", "inspired",
        "inspiring", "instant", "instinctive", "institutional", "instructive",
        "instrumental", "insufficient", "insulated", "insulting", "intact",
        "integral", "integrated", "intellectual", "intelligent", "intelligible",
        "intended", "intense", "intensive", "intentional", "interactive",
        "interested", "interesting", "interior", "intermediate", "intermittent",
        "internal", "international", "interpersonal", "interstate", "interstellar",
        "intertwined", "intimate", "intolerant", "intractable", "intrepid",
        "intricate", "intrigued", "intriguing", "intrinsic", "introductory",
        "introverted", "intrusive", "intuitive", "invaluable", "invasive",
        "inventive", "invigorating", "invisible", "invited", "inviting",
        "involuntary", "involved", "inward", "irate", "irksome",
        "iron", "ironclad", "ironic", "irrational", "irreconcilable",
        "irrefutable", "irregular", "irrelevant", "irreparable",
        "irreplaceable", "irresistible", "irresponsible", "irreverent",
        "irreversible", "irritable", "irritated", "irritating", "isolated",
        "itchy", "itinerant", "jaded", "jagged", "jarring", "jaunty",
        "jazzy", "jealous", "jeering", "jittery", "jobless", "jocular",
        "joint", "jolly", "jovial", "joyful", "joyless", "joyous",
        "jubilant", "judgmental", "judicious", "juicy", "jumbled",
        "jumbo", "jumpy", "junior", "just", "justifiable", "juvenile",
        "kaput", "keen", "key", "kind", "kindly", "kinetic", "kingly",
        "kitschy", "knee", "knobby", "knowing", "knowledgeable", "known",
        "kooky", "kosher", "labored", "laborious", "lackadaisical",
        "lacking", "laconic", "laidback", "lame", "lamentable", "laminated",
        "land", "landmark", "landscape", "languid", "lanky", "lap",
        "lapsed", "large", "lascivious", "last", "lasting", "late",
        "latent", "lateral", "latest", "latter", "laudable", "laughable",
        "lavish", "lawful", "lawless", "lax", "lazy", "leading",
        "leafy", "leaky", "lean", "learned", "least", "leather",
        "leathery", "left", "legal", "legendary", "legible", "legislative",
        "legitimate", "leisurely", "lengthy", "lenient", "lesser",
        "lethal", "level", "lexical", "liable", "liberal", "limited",
        "limitless", "limp", "linear", "lined", "linguistic", "liquid",
        "listless", "literal", "literary", "literate", "litigious",
        "little", "live", "lively", "living", "loaded", "loathsome",
        "local", "located", "locked", "lofty", "logical", "lonely",
        "long", "longing", "longtime", "looming", "loose", "lopsided",
        "lost", "loud", "lovable", "lovely", "loving", "low",
        "lower", "loyal", "lucid", "lucky", "lucrative", "ludicrous",
        "lugubrious", "lukewarm", "luminous", "lumpy", "lunar", "lurid",
        "luscious", "lush", "lustrous", "luxurious", "lying", "lyrical"
    )

    private val conceptPool = listOf(
        "ability", "absence", "acceptance", "access", "achievement", "action",
        "activity", "adventure", "advice", "affection", "agenda", "agreement",
        "ambition", "analysis", "anger", "anxiety", "approach", "approval",
        "atmosphere", "attitude", "authority", "awareness", "balance",
        "barrier", "beauty", "behavior", "belief", "benefit", "bond",
        "boundary", "bravery", "breath", "burden", "calm", "capability",
        "care", "challenge", "change", "character", "choice", "clarity",
        "comfort", "commitment", "communication", "community", "companion",
        "compassion", "competence", "complexity", "confidence", "conflict",
        "connection", "consciousness", "consistency", "contempt", "content",
        "control", "courage", "creativity", "crisis", "curiosity", "damage",
        "danger", "decision", "defense", "definition", "delight", "demand",
        "depth", "desire", "destiny", "destruction", "determination",
        "development", "devotion", "dignity", "dilemma", "direction",
        "discipline", "discovery", "discretion", "distance", "distinction",
        "distress", "diversity", "doubt", "dream", "duty", "ease",
        "economy", "education", "effect", "effort", "elegance", "emotion",
        "empathy", "emphasis", "empire", "energy", "enjoyment", "enthusiasm",
        "essence", "evidence", "evolution", "excellence", "excitement",
        "existence", "expectation", "experience", "expertise", "exploration",
        "expression", "extent", "fairness", "faith", "fame", "familiarity",
        "fate", "fault", "fear", "feeling", "fiction", "fidelity", "focus",
        "force", "form", "fortune", "freedom", "frequency", "friendship",
        "frustration", "function", "future", "generosity", "genius",
        "gentleness", "glory", "goal", "goodness", "grace", "gratitude",
        "grief", "growth", "guidance", "habit", "happiness", "harmony",
        "health", "heart", "height", "heritage", "history", "honesty",
        "honor", "hope", "horizon", "horror", "humanity", "humility",
        "humor", "idea", "identity", "ignorance", "illusion", "imagination",
        "impact", "importance", "impression", "improvement", "independence",
        "influence", "information", "initiative", "innocence", "insight",
        "inspiration", "instinct", "integrity", "intelligence", "intensity",
        "intention", "interest", "interpretation", "intuition", "investigation",
        "investment", "isolation", "jealousy", "journey", "joy", "judgment",
        "justice", "keenness", "kindness", "knowledge", "labor", "language",
        "laughter", "leadership", "learning", "legacy", "level", "liberty",
        "life", "logic", "loneliness", "loss", "love", "loyalty", "luck",
        "magic", "magnitude", "majesty", "management", "manner", "mastery",
        "matter", "meaning", "measurement", "media", "medicine", "memory",
        "mercy", "merit", "method", "mind", "miracle", "mission",
        "mobility", "moderation", "modesty", "moment", "momentum",
        "monopoly", "mood", "morale", "morality", "motion", "motivation",
        "movement", "mystery", "nature", "necessity", "negotiation",
        "nerve", "network", "nightmare", "nobility", "normal", "normality",
        "notion", "novelty", "nurture", "obedience", "object", "objection",
        "objectivity", "obligation", "observation", "obsession", "obstacle",
        "opinion", "opportunity", "opposite", "optimism", "option",
        "order", "organization", "orientation", "originality", "outcome",
        "outlook", "output", "pace", "pain", "panic", "paradox",
        "passion", "past", "patience", "pattern", "peace", "perception",
        "perfection", "performance", "persistence", "perspective", "phase",
        "philosophy", "pleasure", "politics", "popularity", "portion",
        "position", "possession", "possibility", "potential", "poverty",
        "power", "practice", "praise", "precaution", "precedent",
        "precision", "preference", "prejudice", "preparation", "presence",
        "prestige", "principle", "priority", "privilege", "probability",
        "problem", "procedure", "process", "production", "productivity",
        "profession", "profit", "progress", "project", "promise",
        "promotion", "proof", "property", "proportion", "proposal",
        "prospect", "prosperity", "protection", "protest", "pride",
        "principle", "public", "purchase", "purpose", "pursuit",
        "qualification", "quality", "quantity", "quest", "quota",
        "range", "rate", "ratio", "rationale", "reaction", "reality",
        "reason", "reasoning", "reassurance", "recognition", "recommendation",
        "recovery", "reflection", "reform", "refuge", "region",
        "regret", "regulation", "rejection", "relation", "relationship",
        "relevance", "reliability", "relief", "religion", "reluctance",
        "remedy", "reminder", "remorse", "renewal", "repair", "repetition",
        "reputation", "request", "requirement", "research", "resentment",
        "reserve", "residence", "resignation", "resistance", "resolution",
        "resolve", "resource", "respect", "response", "responsibility",
        "rest", "restoration", "restraint", "restriction", "result",
        "retention", "retreat", "revelation", "revenge", "revenue",
        "reverence", "review", "revolution", "reward", "rhythm",
        "richness", "rigor", "risk", "ritual", "rivalry", "role",
        "romance", "routine", "rule", "sacrifice", "safety", "satisfaction",
        "scale", "scarcity", "schedule", "scheme", "scope", "security",
        "sensitivity", "sentence", "sentiment", "separation", "sequence",
        "serenity", "service", "settlement", "severity", "shame",
        "shape", "share", "shelter", "shift", "shock", "significance",
        "silence", "similarity", "simplicity", "sincerity", "skill",
        "society", "solidarity", "solitude", "solution", "sorrow",
        "soul", "sound", "source", "space", "species", "speculation",
        "speed", "spirit", "stability", "standard", "status", "stimulus",
        "strain", "strategy", "strength", "stress", "structure", "struggle",
        "style", "substance", "success", "suffering", "suggestion",
        "superiority", "support", "surprise", "surrender", "survival",
        "suspense", "suspicion", "symmetry", "sympathy", "system",
        "tact", "talent", "task", "team", "temper", "temptation",
        "tendency", "tension", "term", "territory", "terror", "testimony",
        "theme", "theory", "therapy", "thought", "threat", "threshold",
        "thrill", "tolerance", "topic", "tradition", "tragedy", "training",
        "trait", "trance", "tranquility", "transformation", "transition",
        "treasure", "treatment", "trend", "trial", "tribute", "trust",
        "truth", "turning", "tutorial", "uncertainty", "understanding",
        "uniqueness", "unity", "universe", "urgency", "usage", "use",
        "utility", "vacuum", "validity", "value", "variation", "variety",
        "venture", "version", "vibration", "victory", "view", "vigor",
        "virtue", "vision", "vitality", "volume", "vulnerability",
        "warmth", "warning", "waste", "wealth", "weapon", "welfare",
        "wellness", "wholeness", "willingness", " wisdom", "wonder",
        "worth", "worthiness", "wound", "wrath", "yield", "youth", "zeal", "zenith"
    )

    private val generalPool = listOf(
        "action", "answer", "appeal", "approach", "arrival", "aspect",
        "assault", "assistance", "assumption", "attempt", "attention",
        "attraction", "backing", "balance", "barrier", "base", "basis",
        "beginning", "behavior", "belief", "block", "blow", "boost",
        "border", "bottom", "branch", "breach", "break", "breath",
        "bridge", "build", "burst", "campaign", "capture", "career",
        "case", "cause", "center", "chain", "challenge", "champion",
        "channel", "chapter", "charge", "chase", "check", "chief",
        "circle", "circuit", "claim", "class", "clause", "client",
        "climate", "climb", "cluster", "coach", "code", "collapse",
        "collect", "column", "combat", "combine", "command", "comment",
        "commerce", "commission", "commit", "commodity", "compact",
        "company", "comparison", "compass", "compel", "compete",
        "complain", "complement", "complex", "component", "compound",
        "compromise", "compute", "conceal", "concede", "conceive",
        "concept", "concern", "concert", "conclude", "concrete",
        "condition", "conduct", "conference", "confess", "confine",
        "confirm", "conflict", "conform", "confront", "confuse",
        "connect", "conquest", "conscience", "conscious", "consent",
        "consequence", "conservation", "consider", "consist", "console",
        "consolidate", "constant", "constitute", "constrain", "construct",
        "consult", "consume", "contact", "contain", "contemplate",
        "contend", "contest", "context", "contract", "contrast",
        "contribute", "contrive", "control", "controversy", "convene",
        "convention", "converge", "conversation", "conversion", "convey",
        "convict", "convince", "cooperate", "coordinate", "cope",
        "copy", "core", "corner", "corporate", "correct", "correlate",
        "correspond", "corrupt", "counsel", "count", "counter",
        "counterpart", "county", "couple", "course", "court", "covenant",
        "cover", "crack", "craft", "crash", "create", "creature",
        "credit", "crew", "crime", "crisis", "criterion", "critical",
        "crop", "cross", "crowd", "crown", "crucial", "crude",
        "crush", "crystal", "cultivate", "culture", "cure", "curiosity",
        "currency", "current", "curriculum", "curse", "curve", "custody",
        "custom", "cycle", "damage", "danger", "dawn", "deadline",
        "deal", "debate", "debt", "decade", "decay", "deceive",
        "decent", "decide", "decision", "deck", "declare", "decline",
        "decorate", "decrease", "decree", "dedicate", "deed", "defeat",
        "defect", "defend", "defense", "deficit", "define", "definite",
        "degree", "delay", "delegate", "delete", "deliberate", "delicate",
        "delight", "deliver", "demand", "democracy", "demonstrate",
        "denote", "deny", "depart", "depend", "depict", "deposit",
        "depress", "deprive", "depth", "deputy", "derive", "descend",
        "describe", "desert", "deserve", "design", "designate", "desire",
        "desk", "despair", "desperate", "despise", "despite", "destine",
        "destroy", "destruct", "detach", "detail", "detect", "detention",
        "deteriorate", "determine", "develop", "device", "devote",
        "diagnose", "dialogue", "dictate", "differ", "digest", "dignity",
        "dilemma", "dimension", "diminish", "dioxide", "diploma",
        "direct", "disable", "disagree", "disappear", "disappoint",
        "disaster", "discard", "discern", "discharge", "discipline",
        "disclose", "discount", "discourse", "discover", "discreet",
        "discrepancy", "discrete", "discriminate", "discuss", "disease",
        "disgust", "dislike", "dismiss", "disorder", "dispatch",
        "display", "dispose", "disprove", "dispute", "disregard",
        "disrupt", "dissolve", "distance", "distinct", "distinguish",
        "distort", "distract", "distress", "distribute", "district",
        "disturb", "diverse", "divert", "divide", "divine", "division",
        "divorce", "doctrine", "document", "domain", "domestic",
        "dominant", "dominate", "donate", "doom", "dose", "double",
        "doubt", "draft", "drain", "dramatic", "drastic", "drawback",
        "dread", "dream", "dress", "drift", "drop", "drought",
        "drown", "dual", "dubious", "due", "dump", "duplicate",
        "durable", "dwell", "dynamic", "eager", "earn", "ease",
        "echo", "eclipse", "ecology", "economy", "edge", "edition",
        "educate", "effect", "efficient", "effort", "elaborate",
        "elapse", "elastic", "elder", "elect", "elegant", "element",
        "elevate", "elicit", "eligible", "eliminate", "elite",
        "eloquent", "elude", "embark", "embarrass", "embassy", "embed",
        "embody", "embrace", "emerge", "emergency", "eminent", "emission",
        "emotion", "emphasis", "empire", "empirical", "employ", "enable",
        "enclose", "encounter", "encourage", "endanger", "endeavor",
        "endorse", "endow", "endure", "enforce", "engage", "engine",
        "enhance", "enjoy", "enlarge", "enlighten", "enormous", "enrich",
        "enroll", "ensure", "enterprise", "entertain", "enthusiasm",
        "entitle", "entity", "entrance", "entrepreneur", "entry",
        "envelope", "environment", "envy", "epidemic", "episode",
        "equal", "equip", "equivalent", "era", "erect", "erosion",
        "error", "erupt", "escalate", "escape", "escort", "essay",
        "essence", "establish", "estate", "esteem", "estimate",
        "eternal", "ethics", "ethnic", "evaluate", "evaporate",
        "event", "eventual", "evidence", "evident", "evil", "evoke",
        "evolve", "exact", "exaggerate", "examine", "example", "exceed",
        "excellence", "except", "excess", "exchange", "excite",
        "exclude", "exclusive", "excuse", "execute", "exemplify",
        "exercise", "exert", "exhaust", "exhibit", "exile", "exist",
        "exit", "expand", "expanse", "expect", "expedition", "expel",
        "expense", "experiment", "expert", "expertise", "expire",
        "explain", "explicit", "explode", "exploit", "explore",
        "explosion", "export", "expose", "express", "extend", "extent",
        "exterior", "external", "extinct", "extract", "extreme",
        "fabric", "fabricate", "facade", "face", "facilitate", "facility",
        "factor", "faculty", "fade", "fail", "failure", "faint",
        "fair", "faith", "fall", "fame", "familiar", "famine",
        "famous", "fan", "fancy", "fantasy", "fascinate", "fashion",
        "fasten", "fatal", "fate", "fatigue", "fault", "favor",
        "feasible", "feature", "federal", "feeble", "feedback",
        "fellow", "female", "fence", "fertile", "fever", "fiber",
        "fiction", "field", "fierce", "figure", "file", "filter",
        "final", "finance", "finding", "finite", "firm", "fiscal",
        "fixture", "flame", "flash", "flat", "flavor", "flaw",
        "flee", "flexible", "flight", "float", "flock", "flood",
        "flourish", "flow", "fluctuate", "fluid", "focus", "folk",
        "forbid", "force", "forecast", "foreign", "forest", "forever",
        "forfeit", "forgive", "form", "formal", "format", "former",
        "formula", "forth", "fortune", "forum", "forward", "foster",
        "foundation", "fraction", "fragile", "fragment", "frame",
        "framework", "franchise", "frank", "fraud", "free", "freedom",
        "freeze", "freight", "frequency", "frequent", "friction",
        "fringe", "front", "frontier", "frown", "frozen", "fruit",
        "frustrate", "fuel", "fulfill", "function", "fund", "fundamental",
        "funeral", "furious", "furnish", "further", "fury", "fuse",
        "fusion", "future", "gain", "gallery", "gamble", "gap",
        "garbage", "gather", "gauge", "gaze", "gear", "gender",
        "gene", "general", "generate", "generous", "genetic", "genius",
        "genre", "gentle", "genuine", "gesture", "giant", "gift",
        "gigantic", "glacier", "glance", "glare", "global", "globe",
        "gloom", "glory", "gloss", "govern", "grab", "grace",
        "gradual", "graduate", "grain", "grand", "grant", "graphic",
        "grasp", "grateful", "gravity", "great", "greed", "green",
        "greet", "grief", "grind", "grip", "gross", "ground",
        "group", "growth", "guarantee", "guard", "guess", "guest",
        "guide", "guideline", "guilt", "guilty", "habit", "habitat",
        "halt", "handbook", "handful", "handle", "happen", "harbor",
        "harden", "hardship", "hardware", "harm", "harmony", "harness",
        "harsh", "harvest", "hazard", "headline", "heal", "health",
        "heap", "hearing", "heart", "heaven", "height", "heir",
        "heritage", "hero", "hesitate", "hidden", "highlight", "highway",
        "hike", "hinder", "hinge", "hint", "historic", "hollow",
        "honest", "honor", "hook", "horizon", "hormone", "horror",
        "hostile", "household", "hover", "human", "humble", "humor",
        "hunt", "hurt", "hypothesis", "ideal", "identical", "identify",
        "identity", "ideology", "ignorance", "ignore", "illegal",
        "illness", "illusion", "illustrate", "image", "imaginary",
        "imagination", "imitate", "immediate", "immense", "immigrant",
        "immune", "impact", "impatient", "implement", "implicit",
        "imply", "import", "impose", "impress", "impulse", "incentive",
        "incident", "incline", "income", "incorporate", "increase",
        "incredible", "incur", "indeed", "indicate", "indifferent",
        "indigenous", "indirect", "individual", "indoor", "induce",
        "indulge", "industry", "inevitable", "infant", "infect",
        "infer", "inferior", "infinite", "inflation", "influence",
        "inform", "infrastructure", "inhabit", "inherent", "inherit",
        "inhibit", "initial", "initiate", "inject", "injure", "inmate",
        "inner", "innocent", "innovation", "input", "inquiry", "insect",
        "insert", "insight", "insist", "inspect", "inspire", "install",
        "instance", "instant", "instinct", "institute", "instruct",
        "instrument", "insult", "insurance", "intact", "integrate",
        "integrity", "intellectual", "intelligence", "intend", "intense",
        "intensive", "intention", "interact", "interest", "interface",
        "interfere", "interior", "intermediate", "internal", "international",
        "interpret", "interrupt", "interval", "intervene", "intimate",
        "intrigue", "intrinsic", "introduce", "intrude", "intuition",
        "invade", "invent", "invest", "investigate", "invite", "involve",
        "inward", "irony", "irrigate", "isolate", "issue", "item",
        "itself", "jealous", "jeopardy", "joint", "journal", "judge",
        "judgment", "judicial", "junction", "junior", "jury", "justice",
        "justify", "keen", "keep", "kernel", "key", "kick", "kidnap",
        "kind", "kingdom", "kit", "knack", "knot", "know", "knowledge",
        "label", "labor", "laboratory", "lack", "ladder", "lag",
        "landmark", "landscape", "lane", "language", "laser", "last",
        "latent", "lateral", "latest", "launch", "law", "lawn",
        "lawsuit", "lawyer", "layer", "layout", "lead", "leader",
        "leadership", "leaf", "league", "leak", "lean", "leap",
        "learning", "lease", "legacy", "legal", "legend", "legislation",
        "legitimate", "leisure", "lend", "length", "lesson", "level",
        "leverage", "liability", "liberal", "liberty", "license",
        "lifestyle", "lifetime", "lift", "light", "likelihood", "limit",
        "line", "linear", "link", "liquid", "list", "listen",
        "literal", "literary", "literature", "litigation", "livelihood",
        "lobby", "local", "locate", "location", "lodge", "logic",
        "logical", "logo", "longitude", "lookout", "loop", "loose",
        "lord", "loss", "lot", "loud", "lovely", "lover", "low",
        "lower", "loyalty", "luck", "lucky", "luggage", "lump",
        "luxury", "machine", "machinery", "macro", "magazine", "magic",
        "magnet", "magnificent", "magnitude", "main", "mainland",
        "maintain", "maintenance", "major", "majority", "makeup",
        "male", "manage", "management", "mandate", "manifest", "manipulate",
        "manner", "manual", "manufacture", "manuscript", "map", "marathon",
        "marble", "margin", "marine", "mark", "marker", "market",
        "marketing", "marriage", "mask", "mass", "massive", "master",
        "masterpiece", "match", "mate", "material", "mathematics",
        "matter", "mature", "maximum", "mayor", "maze", "meal",
        "meaning", "means", "meantime", "measure", "measurement",
        "mechanic", "mechanism", "media", "mediate", "medical", "medium",
        "meeting", "melody", "melt", "member", "membership", "memo",
        "memoir", "memorandum", "memory", "mental", "mention", "mentor",
        "merchant", "mercy", "mere", "merge", "merit", "mesh", "message",
        "metal", "metaphor", "method", "methodology", "metric", "micro",
        "mid", "middle", "midnight", "midst", "migrant", "migrate",
        "mild", "milestone", "milieu", "military", "millennium", "mimic",
        "mind", "mineral", "mingle", "miniature", "minimal", "minimum",
        "mining", "minister", "ministry", "minor", "minority", "mint",
        "miracle", "mirror", "miserable", "misery", "misfortune",
        "misleading", "miss", "missile", "missing", "mission", "mist",
        "mistake", "misunderstand", "mix", "mixture", "mobile", "mobility",
        "mode", "model", "moderate", "modern", "modest", "modify",
        "module", "moisture", "mold", "molecule", "moment", "momentum",
        "monetary", "monitor", "monopoly", "monster", "monthly", "monument",
        "mood", "moral", "morality", "mortal", "mortgage", "mosaic",
        "motion", "motivate", "motivation", "motive", "motor", "mount",
        "mountain", "mouth", "movement", "multiple", "multiply",
        "multitude", "municipal", "murder", "muscle", "museum", "mushroom",
        "music", "mutual", "mysterious", "mystery", "myth", "mythology",
        "nail", "naive", "narrative", "narrow", "nation", "national",
        "nationalist", "native", "natural", "nature", "naval", "navigation",
        "navy", "near", "nearby", "neat", "necessary", "necessity",
        "negative", "neglect", "negotiate", "negotiation", "neighbor",
        "neighborhood", "neither", "nerve", "nervous", "nest", "net",
        "network", "neutral", "nevertheless", "next", "nice", "niche",
        "nightmare", "noble", "nobody", "node", "noise", "nominal",
        "nominate", "none", "nonprofit", "norm", "normal", "north",
        "northern", "notable", "note", "notebook", "nothing", "notice",
        "notion", "novel", "novelty", "nowhere", "nuclear", "nucleus",
        "nuisance", "number", "numerical", "numerous", "nurse", "nursery",
        "nurture", "nutrient", "nutrition", "object", "objective",
        "obligation", "observe", "obsession", "obstacle", "obtain",
        "obvious", "occasion", "occupation", "occupy", "occur", "ocean",
        "odd", "offense", "offensive", "offer", "office", "officer",
        "official", "offspring", "oil", "old", "olympic", "omission",
        "ongoing", "online", "opening", "operate", "operation",
        "operator", "opinion", "opponent", "opportunity", "oppose",
        "opposite", "opposition", "opt", "optimism", "option", "oral",
        "orbit", "order", "ordinary", "organ", "organic", "organization",
        "organize", "orientation", "origin", "original", "originate",
        "ornament", "other", "outbreak", "outcome", "outdoor",
        "outer", "outline", "outlook", "output", "outrage", "outside",
        "outstanding", "overall", "overcome", "overlook", "overseas",
        "overturn", "overview", "owe", "own", "owner", "ownership",
        "pace", "pack", "package", "page", "pain", "paint", "pair",
        "palace", "pale", "panel", "panic", "parade", "paragraph",
        "parallel", "parameter", "parcel", "parent", "parish", "park",
        "parliament", "part", "partial", "participant", "participate",
        "particle", "particular", "partner", "partnership", "passage",
        "passenger", "passion", "passive", "password", "past", "patch",
        "patent", "path", "patience", "patient", "patrol", "pattern",
        "pause", "pavement", "payment", "peace", "peak", "peer",
        "penalty", "penetrate", "pension", "people", "perceive",
        "perception", "perfect", "perform", "performance", "perfume",
        "perhaps", "period", "permanent", "permission", "permit",
        "persist", "person", "personal", "personality", "personnel",
        "perspective", "persuade", "phase", "phenomenon", "philosophy",
        "phone", "photo", "phrase", "physical", "physician", "physics",
        "piano", "picture", "piece", "pierce", "pile", "pilot",
        "pioneer", "pipe", "pipeline", "pitch", "pity", "place",
        "plain", "plan", "plane", "planet", "plant", "plastic",
        "plateau", "platform", "play", "player", "plea", "pleasant",
        "please", "pleasure", "pledge", "plenty", "plot", "plug",
        "plunge", "plural", "plus", "pocket", "poem", "poet",
        "poetry", "point", "polar", "police", "policy", "polish",
        "polite", "political", "politician", "politics", "poll",
        "pollution", "pond", "pool", "poor", "populate", "population",
        "port", "portable", "portion", "portrait", "pose", "position",
        "positive", "possess", "possession", "possibility", "possible",
        "post", "poster", "potato", "potential", "pound", "pour",
        "poverty", "powder", "power", "powerful", "practical", "practice",
        "practitioner", "praise", "pray", "preach", "precaution",
        "precious", "precise", "predict", "prefer", "preference",
        "pregnant", "prejudice", "preliminary", "premier", "premise",
        "premium", "preparation", "prepare", "prescribe", "prescription",
        "presence", "present", "preserve", "preside", "president",
        "press", "pressure", "prestige", "presume", "pretend", "pretty",
        "prevail", "prevent", "previous", "price", "pride", "priest",
        "primary", "prime", "primitive", "prince", "princess", "principal",
        "principle", "print", "prior", "priority", "prison", "prisoner",
        "privacy", "private", "privilege", "prize", "probability",
        "probable", "probe", "problem", "procedure", "proceed",
        "process", "produce", "product", "production", "productive",
        "profession", "professional", "professor", "profile", "profit",
        "profound", "program", "progress", "prohibit", "project",
        "prominent", "promise", "promote", "prompt", "proof", "propaganda",
        "proper", "property", "proportion", "proposal", "propose",
        "prospect", "protect", "protection", "protein", "protest",
        "protocol", "proud", "prove", "provide", "province", "provision",
        "provoke", "proximity", "psychology", "public", "publication",
        "publicity", "publish", "pull", "pulse", "pump", "punch",
        "punish", "pupil", "purchase", "pure", "purple", "purpose",
        "pursue", "pursuit", "push", "puzzle", "qualification",
        "qualify", "quality", "quantity", "quarter", "queen", "query",
        "quest", "question", "queue", "quick", "quiet", "quit",
        "quite", "quota", "quotation", "quote", "race", "radar",
        "radiation", "radical", "radio", "rage", "raid", "rail",
        "railway", "rain", "raise", "rally", "random", "range",
        "rank", "rapid", "rare", "rate", "rather", "rating", "ratio",
        "rational", "raw", "reach", "react", "reaction", "read",
        "reader", "readily", "reading", "ready", "real", "realistic",
        "reality", "realize", "realm", "rear", "reason", "reasonable",
        "reasoning", "reassure", "rebel", "rebuild", "recall", "receipt",
        "receive", "recent", "reception", "recession", "recipe",
        "recipient", "reckon", "recognition", "recognize", "recommend",
        "recommendation", "reconcile", "record", "recover", "recovery",
        "recreation", "recruit", "recycle", "reduce", "reduction",
        "refer", "reference", "reflect", "reflection", "reform",
        "refresh", "refugee", "refund", "refuse", "region", "register",
        "regret", "regular", "regulate", "regulation", "rehab",
        "rehearsal", "reign", "reinforce", "reject", "relate",
        "relation", "relationship", "relative", "release", "relevant",
        "relief", "religion", "religious", "relocate", "rely",
        "remain", "remainder", "remark", "remarkable", "remedy",
        "remember", "remind", "remote", "remove", "render", "renew",
        "rent", "repair", "repeat", "replace", "reply", "report",
        "represent", "representative", "reproduce", "republic",
        "reputation", "request", "require", "requirement", "rescue",
        "research", "resemble", "reservation", "reserve", "reside",
        "residence", "resident", "resign", "resist", "resistance",
        "resolution", "resolve", "resort", "resource", "respect",
        "respond", "response", "responsibility", "responsible", "rest",
        "restaurant", "restore", "restrict", "restriction", "result",
        "resume", "retail", "retain", "retire", "retreat", "return",
        "reveal", "revenue", "reverse", "review", "revise", "revive",
        "revolution", "reward", "rhetoric", "rhythm", "rich", "rid",
        "ride", "ridge", "ridiculous", "rifle", "right", "rigid",
        "ring", "riot", "rise", "risk", "ritual", "rival", "river",
        "road", "robust", "rocket", "role", "roll", "romance",
        "romantic", "roof", "room", "root", "rope", "rough", "round",
        "route", "routine", "row", "royal", "rub", "rugby", "ruin",
        "rule", "ruler", "rumor", "run", "runner", "rural", "rush",
        "sacred", "sacrifice", "sad", "safe", "safety", "sail",
        "saint", "salary", "sale", "salt", "salute", "sample",
        "sanction", "sand", "satellite", "satisfaction", "satisfy",
        "save", "saving", "scale", "scan", "scandal", "scarce",
        "scatter", "scene", "scenery", "schedule", "scheme", "scholar",
        "scholarship", "school", "science", "scientific", "scientist",
        "scope", "score", "scrap", "scream", "screen", "script",
        "scrutiny", "seal", "search", "season", "seat", "second",
        "secret", "secretary", "section", "sector", "secure", "security",
        "seed", "seek", "segment", "seize", "select", "selection",
        "self", "sell", "senate", "senator", "send", "senior",
        "sense", "sensitive", "sensitivity", "sentence", "sentiment",
        "separate", "separation", "sequence", "serial", "series",
        "serious", "serve", "service", "session", "setback", "setting",
        "settle", "settlement", "setup", "severe", "shade", "shadow",
        "shake", "shall", "shallow", "shame", "shape", "share",
        "sharp", "shatter", "shed", "sheet", "shelf", "shell",
        "shelter", "shift", "shining", "ship", "shock", "shoe",
        "shoot", "shop", "shore", "short", "shortage", "shot",
        "shoulder", "shout", "show", "shower", "shrink", "shrug",
        "shut", "side", "sight", "sign", "signal", "signature",
        "significance", "significant", "silence", "silent", "silk",
        "silly", "silver", "similar", "similarity", "simple", "simplicity",
        "simplify", "simply", "simulate", "simulation", "simultaneous",
        "sin", "since", "sincere", "sing", "singer", "single",
        "singular", "sink", "sir", "sister", "site", "situation",
        "size", "sketch", "skill", "skilled", "skim", "skin",
        "skip", "sky", "skyscraper", "slave", "sleep", "slice",
        "slide", "slight", "slip", "slope", "slow", "small",
        "smart", "smell", "smile", "smoke", "smooth", "snap",
        "snow", "soak", "social", "society", "sock", "soft",
        "software", "soil", "solar", "sole", "solemn", "solid",
        "solidarity", "solution", "solve", "somebody", "somehow",
        "someone", "something", "sometime", "somewhat", "song",
        "soon", "sophisticated", "sore", "sorrow", "sorry", "sort",
        "soul", "sound", "source", "south", "southern", "sovereign",
        "space", "spare", "spark", "speak", "speaker", "special",
        "specialist", "specialty", "species", "specific", "specify",
        "specimen", "spectacle", "spectacular", "spectrum", "speech",
        "speed", "spell", "spend", "sphere", "spill", "spin",
        "spine", "spirit", "spiritual", "spite", "splendid", "split",
        "spokesman", "sponsor", "sport", "spot", "spouse", "spray",
        "spread", "spring", "spy", "square", "squeeze", "stability",
        "stable", "stadium", "staff", "stage", "stain", "stair",
        "stake", "stale", "stamp", "stand", "standard", "standing",
        "star", "stare", "start", "state", "statement", "station",
        "statistic", "statue", "status", "stay", "steady", "steal",
        "steam", "steel", "steep", "steer", "stem", "step", "stereo",
        "stereotype", "stick", "sticky", "stiff", "still", "stimulate",
        "stimulus", "stir", "stock", "stomach", "stone", "stop",
        "storage", "store", "storm", "story", "straight", "strain",
        "strand", "strange", "stranger", "strategy", "stream", "street",
        "strength", "strengthen", "stress", "stretch", "strict",
        "strike", "string", "strip", "stroke", "strong", "structure",
        "struggle", "student", "studio", "study", "stuff", "stupid",
        "style", "subject", "sublime", "submit", "subsequent",
        "subsidy", "substance", "substantial", "substitute", "subtle",
        "suburb", "succeed", "success", "successful", "succession",
        "successive", "suck", "sudden", "suffer", "sufficient",
        "sugar", "suggest", "suggestion", "suicide", "suit", "suitable",
        "suite", "sum", "summary", "summit", "super", "superb",
        "superficial", "superior", "supermarket", "supervise", "supplement",
        "supply", "support", "suppose", "suppress", "supreme", "sure",
        "surface", "surge", "surgeon", "surgery", "surplus", "surprise",
        "surrender", "surround", "survey", "survival", "survive",
        "suspect", "suspend", "suspicion", "suspicious", "sustain",
        "swallow", "swap", "swear", "sweep", "sweet", "swell",
        "swift", "swim", "swing", "switch", "symbol", "symmetry",
        "sympathy", "symptom", "syndrome", "synthesis", "system",
        "table", "tablet", "tackle", "tact", "tactic", "tag",
        "tail", "take", "tale", "talent", "talk", "tank", "tap",
        "tape", "target", "task", "taste", "tax", "taxi", "teach",
        "teacher", "teaching", "team", "tear", "technical", "technique",
        "technology", "teen", "teenage", "teeth", "telephone", "telescope",
        "television", "tell", "temperature", "temple", "temporary",
        "tempt", "tenant", "tend", "tendency", "tender", "tennis",
        "tense", "tension", "tent", "term", "terminal", "terminate",
        "terms", "terrace", "terrible", "terrific", "territory",
        "terror", "test", "testify", "testimony", "testing", "text",
        "textbook", "texture", "theme", "theology", "theory", "therapy",
        "therapist", "there", "thermal", "thesis", "thick", "thief",
        "thin", "thing", "think", "thinking", "third", "thirst",
        "thorn", "thorough", "thought", "thousand", "thread", "threat",
        "threaten", "thrill", "thrive", "throat", "through", "throw",
        "thumb", "ticket", "tide", "tidy", "tie", "tight", "till",
        "timber", "time", "timely", "timing", "tiny", "tip", "tire",
        "tired", "tissue", "title", "today", "together", "toilet",
        "token", "tolerance", "tolerate", "toll", "tone", "tool",
        "tooth", "top", "topic", "torture", "total", "touch",
        "tough", "tour", "tourism", "tourist", "tournament", "toward",
        "tower", "town", "toxic", "trace", "track", "trade", "tradition",
        "traffic", "tragedy", "tragic", "trail", "trailer", "train",
        "training", "trait", "transaction", "transfer", "transform",
        "transformation", "transit", "transition", "translate",
        "transmission", "transmit", "transparent", "transport",
        "transportation", "trap", "trash", "trauma", "travel",
        "treasure", "treat", "treatment", "treaty", "tree", "tremble",
        "tremendous", "trend", "trial", "triangle", "tribe", "tribute",
        "trick", "trigger", "trim", "trip", "triple", "triumph",
        "troop", "trophy", "tropical", "trouble", "truck", "true",
        "truly", "trust", "truth", "try", "tube", "turn", "tutor",
        "tutorial", "twice", "twin", "twist", "type", "typical",
        "ugly", "ultimate", "umbrella", "unable", "unanimous", "uncle",
        "uncover", "under", "undergo", "undergraduate", "undermine",
        "understand", "understanding", "undertake", "undress", "uneasy",
        "unemployment", "unexpected", "unfair", "unfold", "unfortunate",
        "uniform", "union", "unique", "unit", "unite", "unity",
        "universal", "universe", "university", "unknown", "unless",
        "unlike", "unlikely", "unload", "unlock", "lucky", "natural",
        "unnecessary", "unpleasant", "unprecedented", "until", "unusual",
        "update", "upgrade", "uphold", "upon", "upper", "upright",
        "upset", "upstairs", "urban", "urge", "urgent", "usage",
        "use", "used", "useful", "useless", "user", "usual",
        "utility", "utilize", "utmost", "utter", "vacant", "vacation",
        "vacuum", "vague", "valid", "validate", "valley", "valuable",
        "value", "valve", "van", "vanish", "variable", "variation",
        "variety", "various", "vary", "vast", "vehicle", "velocity",
        "vendor", "venture", "venue", "verbal", "verdict", "verify",
        "version", "vertical", "vessel", "veteran", "via", "viable",
        "vibrant", "vibration", "victim", "victory", "video", "view",
        "viewer", "village", "violate", "violation", "violence",
        "violent", "virtual", "virtue", "virus", "visible", "vision",
        "visit", "visitor", "visual", "vital", "vitamin", "vivid",
        "vocabulary", "voice", "volume", "voluntary", "volunteer",
        "vote", "vulnerable", "wage", "wait", "waive", "walk",
        "wall", "wander", "want", "war", "ward", "warehouse",
        "warm", "warmth", "warn", "warning", "warrant", "wash",
        "waste", "watch", "water", "wave", "wax", "way", "weak",
        "weakness", "wealth", "wealthy", "weapon", "wear", "weather",
        "weave", "web", "website", "wedding", "weed", "week",
        "weekend", "weekly", "weigh", "weight", "weird", "welcome",
        "welfare", "well", "west", "western", "wet", "whale",
        "wheel", "when", "where", "whether", "which", "while",
        " whip", "white", "whole", "wholesale", "whom", "whose",
        "wide", "widow", "width", "wife", "wild", "wildlife",
        "will", "willing", "win", "wind", "window", "wine", "wing",
        "winner", "winter", "wipe", "wire", "wisdom", "wise",
        "wish", "wit", "withdraw", "within", "without", "witness",
        "wonder", "wood", "wooden", "word", "work", "worker",
        "workforce", "working", "workout", "workplace", "workshop",
        "world", "worldwide", "worry", "worth", "worthy", "wound",
        "wrap", "wrist", "write", "writer", "writing", "wrong",
        "yard", "year", "yell", "yellow", "yes", "yesterday",
        "yet", "yield", "young", "youth", "zone"
    )

    private val chineseMap: Map<String, String> = mapOf(
        "perseverance" to "毅力；坚持不懈",
        "persistence" to "坚持；持续",
        "endurance" to "忍耐；耐力",
        "determination" to "决心；果断",
        "resilience" to "韧性；恢复力",
        "patience" to "耐心；忍耐",
        "diligence" to "勤奋；勤勉",
        "tenacity" to "顽强；固执",
        "commitment" to "承诺；投入",
        "tenacious" to "顽强的",
        "dogged" to "顽强的；固执的",
        "stubborn" to "固执的",
        "relentless" to "不懈的",
        "unwavering" to "不动摇的",
        "stamina" to "耐力；精力",
        "tolerance" to "容忍；宽容",
        "fortitude" to "坚韧；刚毅",
        "resistance" to "抵抗；阻力",
        "fatigue" to "疲劳；疲乏",
        "resolve" to "决心；解决",
        "willpower" to "意志力",
        "dedication" to "奉献；专注",
        "ambition" to "雄心；抱负",
        "hesitation" to "犹豫；踌躇",
        "adaptability" to "适应性",
        "flexibility" to "灵活性",
        "recovery" to "恢复；复原",
        "fragility" to "脆弱；易碎",
        "buoyancy" to "浮力；乐观",
        "composure" to "镇静；沉着",
        "impulsiveness" to "冲动",
        "persevere" to "坚持不懈",
        "calmness" to "平静；冷静",
        "industrious" to "勤奋的",
        "assiduous" to "刻苦的",
        "lazy" to "懒惰的",
        "conscientious" to "认真的",
        "effort" to "努力",
        "grit" to "勇气；毅力",
        "obstinate" to "倔强的",
        "yield" to "屈服；让步",
        "steely" to "钢铁般的",
        "backbone" to "骨干；骨气",
        "devotion" to "奉献；热爱",
        "loyalty" to "忠诚；忠心",
        "apathy" to "冷漠；无动于衷",
        "responsibility" to "责任",
        "engagement" to "参与；约定"
    )

    private val phoneticMap: Map<String, String> = mapOf(
        "perseverance" to "/pɜːsəˈvɪərəns/",
        "persistence" to "/pəˈsɪstəns/",
        "endurance" to "/ɪnˈdjʊərəns/",
        "determination" to "/dɪˌtɜːmɪˈneɪʃən/",
        "resilience" to "/rɪˈzɪliəns/",
        "patience" to "/ˈpeɪʃəns/",
        "diligence" to "/ˈdɪlɪdʒəns/",
        "tenacity" to "/tɪˈnæsɪti/",
        "commitment" to "/kəˈmɪtmənt/",
        "tenacious" to "/tɪˈneɪʃəs/",
        "dogged" to "/ˈdɒɡɪd/",
        "stubborn" to "/ˈstʌbən/",
        "relentless" to "/rɪˈlentləs/",
        "unwavering" to "/ʌnˈweɪvərɪŋ/",
        "stamina" to "/ˈstæmɪnə/",
        "tolerance" to "/ˈtɒlərəns/",
        "fortitude" to "/ˈfɔːtɪtjuːd/",
        "resistance" to "/rɪˈzɪstəns/",
        "fatigue" to "/fəˈtiːɡ/",
        "resolve" to "/rɪˈzɒlv/",
        "willpower" to "/ˈwɪlˌpaʊə/",
        "dedication" to "/ˌdedɪˈkeɪʃən/",
        "ambition" to "/æmˈbɪʃən/",
        "hesitation" to "/ˌhezɪˈteɪʃən/",
        "adaptability" to "/əˌdæptəˈbɪlɪti/",
        "flexibility" to "/ˌfleksɪˈbɪlɪti/",
        "recovery" to "/rɪˈkʌvəri/",
        "fragility" to "/frəˈdʒɪlɪti/",
        "buoyancy" to "/ˈbɔɪənsi/",
        "composure" to "/kəmˈpəʊʒə/",
        "impulsiveness" to "/ɪmˈpʌlsɪvnəs/",
        "persevere" to "/ˌpɜːsɪˈvɪə/",
        "calmness" to "/ˈkɑːmnəs/",
        "industrious" to "/ɪnˈdʌstriəs/",
        "assiduous" to "/əˈsɪdjuəs/",
        "lazy" to "/ˈleɪzi/",
        "conscientious" to "/ˌkɒnʃiˈenʃəs/",
        "effort" to "/ˈefət/",
        "grit" to "/ɡrɪt/",
        "obstinate" to "/ˈɒbstɪnət/",
        "yield" to "/jiːld/",
        "steely" to "/ˈstiːli/",
        "backbone" to "/ˈbækbəʊn/",
        "devotion" to "/dɪˈvəʊʃən/",
        "loyalty" to "/ˈlɔɪəlti/",
        "apathy" to "/ˈæpəθi/",
        "responsibility" to "/rɪˌspɒnsəˈbɪlɪti/",
        "engagement" to "/ɪnˈɡeɪdʒmənt/"
    )
}
